# Generated by CMake 2.8.8

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target boost_thread
ADD_LIBRARY(boost_thread STATIC IMPORTED)

# Create imported target boost_system
ADD_LIBRARY(boost_system STATIC IMPORTED)

# Import target "boost_thread" for configuration "Debug"
SET_PROPERTY(TARGET boost_thread APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(boost_thread PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/boost/libs/thread/Debug/boost_thread.lib"
  )

# Import target "boost_system" for configuration "Debug"
SET_PROPERTY(TARGET boost_system APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(boost_system PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/boost/libs/system/Debug/boost_system.lib"
  )

# Import target "boost_thread" for configuration "Release"
SET_PROPERTY(TARGET boost_thread APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(boost_thread PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/boost/libs/thread/Release/boost_thread.lib"
  )

# Import target "boost_system" for configuration "Release"
SET_PROPERTY(TARGET boost_system APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(boost_system PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/boost/libs/system/Release/boost_system.lib"
  )

# Import target "boost_thread" for configuration "MinSizeRel"
SET_PROPERTY(TARGET boost_thread APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
SET_TARGET_PROPERTIES(boost_thread PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/boost/libs/thread/MinSizeRel/boost_thread.lib"
  )

# Import target "boost_system" for configuration "MinSizeRel"
SET_PROPERTY(TARGET boost_system APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
SET_TARGET_PROPERTIES(boost_system PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/boost/libs/system/MinSizeRel/boost_system.lib"
  )

# Import target "boost_thread" for configuration "RelWithDebInfo"
SET_PROPERTY(TARGET boost_thread APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
SET_TARGET_PROPERTIES(boost_thread PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/boost/libs/thread/RelWithDebInfo/boost_thread.lib"
  )

# Import target "boost_system" for configuration "RelWithDebInfo"
SET_PROPERTY(TARGET boost_system APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
SET_TARGET_PROPERTIES(boost_system PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/boost/libs/system/RelWithDebInfo/boost_system.lib"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.8.8

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target ScriptingCore
ADD_LIBRARY(ScriptingCore STATIC IMPORTED)

# Import target "ScriptingCore" for configuration "Debug"
SET_PROPERTY(TARGET ScriptingCore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(ScriptingCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_thread;boost_system"
  IMPORTED_LOCATION_DEBUG "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/ScriptingCore/Debug/ScriptingCore.lib"
  )

# Import target "ScriptingCore" for configuration "Release"
SET_PROPERTY(TARGET ScriptingCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(ScriptingCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_thread;boost_system"
  IMPORTED_LOCATION_RELEASE "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/ScriptingCore/Release/ScriptingCore.lib"
  )

# Import target "ScriptingCore" for configuration "MinSizeRel"
SET_PROPERTY(TARGET ScriptingCore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
SET_TARGET_PROPERTIES(ScriptingCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "boost_thread;boost_system"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/ScriptingCore/MinSizeRel/ScriptingCore.lib"
  )

# Import target "ScriptingCore" for configuration "RelWithDebInfo"
SET_PROPERTY(TARGET ScriptingCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
SET_TARGET_PROPERTIES(ScriptingCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "boost_thread;boost_system"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/ScriptingCore/RelWithDebInfo/ScriptingCore.lib"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.8.8

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target PluginCore
ADD_LIBRARY(PluginCore STATIC IMPORTED)

# Import target "PluginCore" for configuration "Debug"
SET_PROPERTY(TARGET PluginCore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(PluginCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/PluginCore/Debug/PluginCore.lib"
  )

# Import target "PluginCore" for configuration "Release"
SET_PROPERTY(TARGET PluginCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(PluginCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/PluginCore/Release/PluginCore.lib"
  )

# Import target "PluginCore" for configuration "MinSizeRel"
SET_PROPERTY(TARGET PluginCore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
SET_TARGET_PROPERTIES(PluginCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/PluginCore/MinSizeRel/PluginCore.lib"
  )

# Import target "PluginCore" for configuration "RelWithDebInfo"
SET_PROPERTY(TARGET PluginCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
SET_TARGET_PROPERTIES(PluginCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/PluginCore/RelWithDebInfo/PluginCore.lib"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.8.8

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target NpapiCore
ADD_LIBRARY(NpapiCore STATIC IMPORTED)

# Import target "NpapiCore" for configuration "Debug"
SET_PROPERTY(TARGET NpapiCore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(NpapiCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_thread;boost_system"
  IMPORTED_LOCATION_DEBUG "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/NpapiCore/Debug/NpapiCore.lib"
  )

# Import target "NpapiCore" for configuration "Release"
SET_PROPERTY(TARGET NpapiCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(NpapiCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_thread;boost_system"
  IMPORTED_LOCATION_RELEASE "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/NpapiCore/Release/NpapiCore.lib"
  )

# Import target "NpapiCore" for configuration "MinSizeRel"
SET_PROPERTY(TARGET NpapiCore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
SET_TARGET_PROPERTIES(NpapiCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "boost_thread;boost_system"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/NpapiCore/MinSizeRel/NpapiCore.lib"
  )

# Import target "NpapiCore" for configuration "RelWithDebInfo"
SET_PROPERTY(TARGET NpapiCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
SET_TARGET_PROPERTIES(NpapiCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "boost_thread;boost_system"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/NpapiCore/RelWithDebInfo/NpapiCore.lib"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.8.8

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target ActiveXCore
ADD_LIBRARY(ActiveXCore STATIC IMPORTED)

# Import target "ActiveXCore" for configuration "Debug"
SET_PROPERTY(TARGET ActiveXCore APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(ActiveXCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_thread;boost_system;PluginCore;ScriptingCore"
  IMPORTED_LOCATION_DEBUG "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/ActiveXCore/Debug/ActiveXCore.lib"
  )

# Import target "ActiveXCore" for configuration "Release"
SET_PROPERTY(TARGET ActiveXCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(ActiveXCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_thread;boost_system;PluginCore;ScriptingCore"
  IMPORTED_LOCATION_RELEASE "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/ActiveXCore/Release/ActiveXCore.lib"
  )

# Import target "ActiveXCore" for configuration "MinSizeRel"
SET_PROPERTY(TARGET ActiveXCore APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
SET_TARGET_PROPERTIES(ActiveXCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "boost_thread;boost_system;PluginCore;ScriptingCore"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/ActiveXCore/MinSizeRel/ActiveXCore.lib"
  )

# Import target "ActiveXCore" for configuration "RelWithDebInfo"
SET_PROPERTY(TARGET ActiveXCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
SET_TARGET_PROPERTIES(ActiveXCore PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "boost_thread;boost_system;PluginCore;ScriptingCore"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/ActiveXCore/RelWithDebInfo/ActiveXCore.lib"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.8.8

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target UnitTest++
ADD_LIBRARY(UnitTest++ STATIC IMPORTED)

# Import target "UnitTest++" for configuration "Debug"
SET_PROPERTY(TARGET UnitTest++ APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(UnitTest++ PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/unittest-cpp/UnitTest++/Debug/UnitTest++.lib"
  )

# Import target "UnitTest++" for configuration "Release"
SET_PROPERTY(TARGET UnitTest++ APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(UnitTest++ PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/unittest-cpp/UnitTest++/Release/UnitTest++.lib"
  )

# Import target "UnitTest++" for configuration "MinSizeRel"
SET_PROPERTY(TARGET UnitTest++ APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
SET_TARGET_PROPERTIES(UnitTest++ PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/unittest-cpp/UnitTest++/MinSizeRel/UnitTest++.lib"
  )

# Import target "UnitTest++" for configuration "RelWithDebInfo"
SET_PROPERTY(TARGET UnitTest++ APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
SET_TARGET_PROPERTIES(UnitTest++ PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/Users/Mauke/Documents/muhkuh/ambientLib/npapi_activex_plugin/firebreath-1.5.2/unittest-cpp/UnitTest++/RelWithDebInfo/UnitTest++.lib"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
